version: '3.8'

services:
  gateway:
    image: linhnd66/metadoc:gateway
    hostname: gateway
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

  auth:
    image: linhnd66/metadoc:auth
    restart: always
    hostname: auth
    ports:
      - "8081:8081"
    command: python main.py
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
  
  docker-visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - '8080:8080'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - "node.role==manager"